/*
 * Copyright (C) 2015- Supership Inc.
 */
package jp.supership.elasticsearch.plugin.queryparser;

import java.io.IOException;
import java.io.Reader;
import java.util.ArrayList;
import java.util.List;
import org.antlr.v4.runtime.ANTLRInputStream;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.Token;
import org.antlr.v4.runtime.misc.ParseCancellationException;
import org.antlr.v4.runtime.tree.ParseTree;
import org.apache.lucene.analysis.Analyzer;
import org.apache.lucene.search.BooleanClause;
import org.apache.lucene.search.Query;
import org.apache.lucene.util.Version;
import jp.supership.elasticsearch.plugin.queryparser.antlr.v4.dsl.QueryBaseVisitor;
import jp.supership.elasticsearch.plugin.queryparser.antlr.v4.dsl.QueryLexer;
import jp.supership.elasticsearch.plugin.queryparser.antlr.v4.dsl.QueryParser;
import jp.supership.elasticsearch.plugin.queryparser.antlr.v4.util.HandleException;
import jp.supership.elasticsearch.plugin.queryparser.antlr.v4.util.QueryHandler;
import jp.supership.elasticsearch.plugin.queryparser.lucene.util.ParseException;
import jp.supership.elasticsearch.plugin.queryparser.lucene.util.QueryEngine;
import jp.supership.elasticsearch.plugin.queryparser.util.StringUtils;


/**
 * This class is responsible for handling query parser generated by ANTLR4 and dispatches internal
 * Lucene APIs through the internal QueryEngine implementation.
 * The utilizing parser is generated by {@code jp.supership.elasticsearch.plugin.dsl.Query#g4},
 * hence the corresponding grammer is for "user land" queries.
 *
 * @author Shingo OKAWA
 * @since  1.0
 */
public class DSQHandler extends QueryBaseVisitor<Query> implements QueryHandler {
    /**
     * Represents domain specific query context, besides holding the query constructing settings
     * this class is also responsible to maintain the currently constructing {@code Query} instance
     * which will be handled with the {@code DSQHandler.Engine}.
     */
    private class Context extends QueryHandler.Context {
	/** Holds currently constructing query. */
	public Query query = null;
	/** Holds constructing clauses. */
	public List<BooleanClause> clauses = new ArrayList<BooleanClause>();
	/** Holds previously detected cunjuntion. */
	public int conjunction = -1;
	/** Holds previously detected modifier. */
	public int modifier = -1;
    }

    /**
     * This class is responsible for instanciating Lucene queries from the Supership, inc. Domain Specific Query.
     */
    private class Engine extends QueryEngine {
        /** Holds query engine which is reponsible for parsing raw query strings. */
        private QueryHandler handler;

	/**
	 * Constructor.
	 */
	public Engine(QueryHandler handler) {
	    this.handler = handler;
	}

        /**
         * {@inheritDoc}
         */
        @Override
        public Query handle(String defaultField) throws HandleException {
            return this.handler.handle(defaultField);
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public Query dispatchBareToken(QueryHandler.Context context) throws HandleException {
            Query query;

            try {
                if (context.wildcard) {
                    query = this.getWildcardQuery(context.field, context.term);
                } else if (context.prefix) {
                    query = this.getPrefixQuery(context.field, StringUtils.discardEscapeChar(context.term.substring(0, context.term.length() - 1)));
                } else if (context.regexp) {
                    query = this.getRegexpQuery(context.field, context.term.substring(1, context.term.length() - 1));
                } else if (context.fuzzy) {
                    query = this.forwardFuzzyQuery(context.field, context.fuzzySlop, context.term);
                } else {
                    query = this.getFieldQuery(context.field, context.term, false);
                }
            } catch (ParseException cause) {
                throw new HandleException(cause);
            }

            return query;
        }

        /**
         * Forwarding to {@code getFuzzyQuery} method with assigned minimum similarity value.
	 * @param  field the currently handling field.
	 * @param  fuzzySlop the currently handling fuzzly slop term.
	 * @param  term  the currently handling term.
	 * @throws ParseException if the parsing fails.
         */
        private Query forwardFuzzyQuery(String field, String fuzzySlop, String term) throws ParseException {
            float fuzzyMinSim = this.getFuzzyMinSim();

            try {
                // TODO: bit legacy code, so depends on the JRE version, fix this code.
                fuzzyMinSim = Float.valueOf(fuzzySlop.substring(1)).floatValue();
            } catch (Exception ignorance) {
                // DO NOTHING, the value has its default, so this is safe.
            }

            if (fuzzyMinSim < 0.0f) {
                throw new ParseException("minimum similarity for a FuzzyQuery must be between 0.0f and 1.0f.");
            } else if (fuzzyMinSim >= 1.0f && fuzzyMinSim != (int) fuzzyMinSim) {
                throw new ParseException("fractional edit distances are not allowed.");
            }

            return this.getFuzzyQuery(field, term, fuzzyMinSim);
        }

	/**
         * {@inheritDoc}
         */
        @Override
        public Query dispatchQuotedToken(QueryHandler.Context context) throws HandleException {
	    int phraseSlop = this.getPhraseSlop();
	    if (context.fuzzySlop != null) {
		try {
		    phraseSlop = Float.valueOf(context.fuzzySlop.substring(1)).intValue();
		}
		catch (Exception ignored) {
		    // DO NOTHING, the value has its default, so this is safe.
		}
	    }
	    return this.getFieldQuery(context.field, StringUtils.discardEscapeChar(context.term.substring(1, context.term.length() - 1)), phraseSlop);
        }

        /**
         * {@inheritDoc}
         */
        @Override
        public void fetch(Reader input) {
            this.handler.fetch(input);
        }
    }

    /** Holds this handler's context. */
    private DSQHandler.Context context;

    /** Holds query engine which is reponsible for parsing raw query strings. */
    private QueryEngine engine;

    /** Holds query engine which is reponsible for parsing raw query strings. */
    private Reader input;

    /**
     * Constructor.
     */
    public DSQHandler() {
	this.engine = new Engine(this);
	this.context = new DSQHandler.Context();
    }

    /**
     * Constructor.
     */
    public DSQHandler(String field, Analyzer analyzer) {
	this();
	this.engine.initialize(field, analyzer);
    }

    /**
     * Constructor.
     */
    public DSQHandler(Version version, String field, Analyzer analyzer) {
	this();
	this.engine.initialize(version, field, analyzer);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Query visitQuery(QueryParser.QueryContext context) {
	try {
	    for (QueryParser.ExpressionContext expression : context.expression()) {
		this.context.conjunction = context.conjunction == null ? QueryParser.CONJUNCTION_AND : context.conjunction.getType();
		this.context.query = visit(expression);
		this.engine.conjugate(this.context.clauses, this.context.conjunction, this.context.modifier, this.context.query);
	    }

	    if (this.context.clauses.size() == 1 && this.context.query != null) {
		return this.context.query;
	    } else {
		return this.engine.getBooleanQuery(this.context.clauses);
	    }
	} catch (Exception cause) {
	    throw new ParseCancellationException(cause);
	}
    }

    /**b
     * {@inheritDoc}
     */
    @Override
    public Query visitExpression(QueryParser.ExpressionContext context) {
	try {
	    this.context.modifier = context.modifier == null ? QueryParser.MODIFIER_REQUIRE : context.modifier.getType();
	    this.context.field = context.FIELD().getText();
	    return visit(context.term());
	} catch (Exception cause) {
	    throw new ParseCancellationException(cause);
	}
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Query visitStringTerm(QueryParser.StringTermContext context) {
	try {
	    this.context.term = context.TERM_STRING().getText();
	    return this.dispatchQuotedToken(this.context);
	} catch (Exception cause) {
	    throw new ParseCancellationException(cause);
	}
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Query visitNumberTerm(QueryParser.NumberTermContext context) {
	try {
	    this.context.term = context.TERM_NUMBER().getText();
	    return this.dispatchBareToken(this.context);
	} catch (Exception cause) {
	    throw new ParseCancellationException(cause);
	}
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Query visitFieldTerm(QueryParser.FieldTermContext context) {
	try {
	    this.context.term = context.TERM_FIELD().getText();
	    return this.dispatchBareToken(this.context);
	} catch (Exception cause) {
	    throw new ParseCancellationException(cause);
	}
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Query visitSubQueryTerm(QueryParser.SubQueryTermContext context) {
	try {
	    return visit(context.query());
	} catch (Exception cause) {
	    throw new ParseCancellationException(cause);
	}
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Query handle(String defaultField) throws HandleException {
        try {
	    // TODO: Check if a fast input stream must be implemented.
            ANTLRInputStream input = new ANTLRInputStream(this.input);
            QueryLexer lexer = new QueryLexer(input);
            CommonTokenStream tokens = new CommonTokenStream(lexer);
            QueryParser parser = new QueryParser(tokens);
            ParseTree tree = parser.query();
            return this.visit(tree);
        } catch (Exception cause) {
            throw new HandleException(cause);
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Query dispatchBareToken(QueryHandler.Context context) throws HandleException {
        return this.engine.dispatchBareToken(context);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Query dispatchQuotedToken(QueryHandler.Context context) throws HandleException {
        return this.engine.dispatchQuotedToken(context);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void fetch(Reader input) {
        this.input = input;
    }
}
